name: R-CMD-check

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          # Add commands here if you need system dependencies, e.g.:
          # sudo apt-get install -y libxml2-dev
          # otherwise, can remain empty

      - name: Set up R
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: rcmdcheck

      - name: Check
        run: |
          R CMD build .
          R CMD check *tar.gz --as-cran
