name: R-CMD-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install Dependencies
        run: Rscript -e 'install.packages("devtools"); devtools::install_deps(dependencies = TRUE)'
      - name: Run R CMD check
        run: R CMD check .
